[vonage]
api_key = "a2d0e8f2"
api_secret = "AlSGSrxv87WnGlZC"
from_number = "14157386102"
whitelist = ["27842078669", "27670127239"]

[google]
spreadsheet_url = "https://docs.google.com/spreadsheets/d/1HXHEYpFXq4MkZdB-J8IuH0_33EeQwJyKVKSkDofD2G8/edit?usp=sharing"

