
[google]
spreadsheet_url = "https://docs.google.com/spreadsheets/d/1HXHEYpFXq4MkZdB-J8IuH0_33EeQwJyKVKSkDofD2G8/edit?usp=sharing"
json_key = """{
  "type": "service_account",
  "project_id": "kidconnect-whatsapp-bot",
  "private_key_id": "20a30092cd3fbf69263dee71093201cb9b358d40",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3EBoLOhKYES5V...",
  "client_email": "kidconnect-bot@kidconnect-whatsapp-bot.iam.gserviceaccount.com",
  "client_id": "117960142838768407666",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/kidconnect-bot%40kidconnect-whatsapp-bot.iam.gserviceaccount.com",
  "universe_domain": "googleapis.com"
}"""

[vonage]
api_key = "a2d0e8f2"
api_secret = "AlSGSrxv87WnGlZC"
from_number = "14157386102"
