[vonage]
api_key = "a2d0e8f2"
api_secret = "AlSGSrxv87WnGlZC"
from_number = "14157386102"
whitelist = ["27842078669", "27670127239"]

[google]
spreadsheet_url = "https://docs.google.com/spreadsheets/d/1HXHEYpFXq4MkZdB-J8IuH0_33EeQwJyKVKSkDofD2G8/edit?gid=410520760#gid=410520760"

[google_service_account]
type = "service_account"
project_id = "kidconnect-whatsapp-bot"
private_key_id = "20a30092cd3fbf69263dee71093201cb9b358d40"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3EBoLOhKYES5V
VD+pGOjk87163pCfS3oMbM9d7LMiS3y6bu5eibqYees2Oq0g+a8q3CXzSPgeF2EJ
OvauN87vGyR8z8UL38xbl5n94nW0VStvK4u82i+wOwr+M27G/rTUvK6r+d+xPRDt
pKBUH8kDxUfylRMYTxkCwA3w/Uni3JZIHI9XdvBlYqnJQs+KHSS2FN7YQ8UufluX
CGoTUcPMAnFQ+w2bKIXf9GbRTmSnKbFahXAm66QD1Iyj0BzXudEmU7b3XpmHAhFu
/kWzFC3dQiSzr2Ab4fXUSaICpY0V0UbsG4Yo2ikH+4ArSz+JIQW5Qa9p86AXFs3r
loY3Ge2dAgMBAAECggEABHMKZ+Yd4umkb4ryASooDS+mh8fEn6jEMjPIK9WU9s6m
AIyxsEU27n3PObsW6+8lqB3qlVSGCKb6mFtITkkM9214kgHQHZY2fcqG1zMbqUZo
q2d//fqk9THPhF4tb4xPg4bZm41axhB9A4KLDblGRe2iCu4GbFfxmQMR/le35cuk
/9g5PNMifp7qNEagMfZ41416iVO98CFHCubK7e0PDAdPTUmifLFJErPgeyjhR4IT
EHocShx5UL+DXffhColKIsu1Z2ZEOMdjKpDF8Msn0RB+jOej0iPGxzhmtWT503Rt
0hpzFKqxvu2cVrmaumr3LkGmvDs8hjp3if4ILHsgAQKBgQD6e8g1DS/BCv3FR2a3
ULNXLbpzXvlB5QMxrInWQTCGDvEEg8PJRfPS4BnM2sqpV0D9ts1dIjcBPmdai6D5
U4Ib+E+0CKCnslNsLAut8UhXPsQYwGxT35ewULVpEXs/t9l3RWme1z4IUDaFraJe
ksnKJrRzSW19dVXz6VeBfjt0IwKBgQC7GDRSVgECNr0wR7nyjunH2Z+DPLXqqi25
rEVaxtiVtOdRfceWvpl8pOpgHicpP/EAqHVze5U6XEsbEhdMRWoZhe76uAJc12NM
FyvwpefiFXFAXkRcF6P7LNqOJ0mSAxsI4xR/vxw9dQQGXY/JvpGMFyHcd6K6ZXyj
k+wZUXtTPwKBgQCdDuJhSWxpCcBHY9bnGMXq4vRnBOUbyUIwcnRXELchR9seLpSj
7qXM0tG6nnG2rsxEicvJGvwMXpmlr6l2zELn0NIBG+vIWstuJ0wHfCQU+Hky3+zM
xoUxe9nUEK8MK/ZCkBaDD4mI4urc9Ru7WyUGCTDanO73XIxRjT1eJ82VqwKBgQCa
tbQmVan126/r6ZPw6I6WzPUjf6NqjhjLjZG4M+/LM9GISHsvwyKGuJR6sNRvPsma
YrLksM/Ad6s/kmEjl87Zli/8sQZ7ITyiIhMapwYtpM+Gi6z5fi8CN5/uprwmelzz
p1s/G5hNlaKjZODO0b/nWQWOGnu8qMk9NseoVAGn3wKBgHHo4UQxYER44be8WSeW
KA2w1W+S2fj6UGb0FQ/0VxtNpZTatRUfkctNuh2o6nHAzCzNk9f5wFnuW0LT9NY5
5fFVPKsLwlbjAerW75aj7aULROeV+wlyLc7lW+yxZJI3kBh+DpxMfK8BfN+TacUR
AOhPMYqsG1af2qsSg8lBtxCI
-----END PRIVATE KEY-----"""
client_email = "kidconnect-bot@kidconnect-whatsapp-bot.iam.gserviceaccount.com"
client_id = "117960142838768407666.apps.googleusercontent.com"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/kidconnect-bot%40kidconnect-whatsapp-bot.iam.gserviceaccount.com"
universe_domain = "googleapis.com"


