[vonage]
api_key = "a2d0e8f2"
api_secret = "AlSGSrxv87WnGlZC"
from_number = "14157386102"
whitelist = ["27842078669", "27670127239"]

[google]
spreadsheet_url = "https://docs.google.com/spreadsheets/d/1HXHEYpFXq4MkZdB-J8IuH0_33EeQwJyKVKSkDofD2G8/edit?usp=sharing"

[google_service_account]
type = "service_account"
project_id = "your-project-id"
private_key_id = "xxx"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC3EBoLOhKYES5V...
-----END PRIVATE KEY-----"""
client_email = "your-service-account-email"
client_id = "xxx"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/your-service-account-email"
